### ISSUE TITLE
about training loss?

### ISSUE THREAD

**Issue by AndyYuan96** [xinge008/SSN#2]
Hi, xinge, the improve of SSN looks very good,  just add another 9 channel for each anchor, and for those positive anchors, use the 9 channel to regression the cooresponding gt's SS, does it right?
For SS, just crop the points in gt, and calculate the shape signature?

**Comment by xinge008** [comment]
Thanks for your attention.

Yes, for shape signature objective, you just need to modify the code_size of regression with 9 more channels, and for shape-aware grouping heads, it is also easy to involve in current frameworks. 

For nuScenes dataset, since its output has additional velocity and attr, some more steps need to process. For Lyft dataset, the mentioned above is all your change. 

We will release the whole code after publication asap.
